[package]
name = "private-context-core"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed.workspace = true
serde.workspace = true
anyhow.workspace = true
reclaim-rust-sdk = { version = "0.1.0", optional = true }
serde_json = "1.0"

[features]
default = ["reclaim-rust-sdk"]
